### ISSUE TITLE
how to fix this problem? pls help 

### ISSUE THREAD

**Issue by tws0002** [listyque/TACTIC-Handler#1]
Traceback (most recent call last):
  File "C:\Program Files (x86)\TACTIC 4.4\TACTIC_handler\main_standalone.pyw", line 11, in <module>
    DATA_DIR = os.environ['TACTIC_DATA_DIR'] + '/TACTIC_handler'
  File "C:\Python27\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'TACTIC_DATA_DIR'

**Comment by listyque** [comment]
Add TACTIC_DATA_DIR to your Os environment.
for example your tactic data dir is here: d:/tactic/tacticdata
then copy TACTIC_handler to this dir, and add environment variable named TACTIC_DATA_DIR with this value "d:/tactic/tacticdata"
