### ISSUE TITLE
Error when running in maya or standalone

### ISSUE THREAD

**Issue by quaam** [listyque/TACTIC-Handler#3]
Hello! I previously posted about an error that I was able to fix by fixing some environment variables and installing the enterprise edition. 

But now I am getting a different error after configuring everything This is the error in the standalone script.

```
Traceback (most recent call last):
  File "C:\TACTIC-Handler\main_standalone.pyw", line 106, in <lambda>
    ping_thread = tc.get_server_thread(dict(), tc.server_ping, lambda: create_ui(ping_thread), parent=app)
  File "C:\TACTIC-Handler\main_standalone.pyw", line 84, in create_ui
    window = ui_main_classes.Ui_Main(parent=None)
  File "C:\TACTIC-Handler\lib\ui_classes\ui_main_classes.py", line 35, in __init__
    env.Env.get_default_dirs()
  File "C:\TACTIC-Handler\lib\environment.py", line 222, in get_default_dirs
    base_dirs = tc.server_start().get_base_dirs()
  File "C:\TACTIC-Handler\lib\side\client\tactic_client_lib\tactic_server_stub.py", line 3144, in get_base_dirs
    return my.server.get_base_dirs(my.ticket)
  File "C:\Python27\lib\xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "C:\Python27\lib\xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "C:\Python27\lib\xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Python27\lib\xmlrpclib.py", line 1313, in single_request
    return self.parse_response(response)
  File "C:\Python27\lib\xmlrpclib.py", line 1490, in parse_response
    return u.close()
  File "C:\Python27\lib\xmlrpclib.py", line 799, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: 'No project [VFX] exists'>
```

And this is the error in the Maya script:

```
TACTIC Server Ping: OK
# Error: Fault: file C:\Program Files\Autodesk\Maya2016\bin\python27.zip\xmlrpclib.py line 793: <Fault 1: 'No project [VFX] exists'> #
```

This is the error in the Tactic Server terminal:

```
127.0.0.1 - - [08/Sep/2016:13:44:03] "POST /tactic/default/Api/ HTTP/1.1" 200 128 "" "xmlrpclib.py (Windows)"
[08/Sep/2016:13:44:04] HTTP 
Request Headers:
  X-FORWARDED-SERVER: 192.168.0.2
  HOST: 192.168.0.2
  CONNECTION: Keep-Alive
  Remote-Addr: 127.0.0.1
  Content-Length: 476
  USER-AGENT: xmlrpclib.py (Windows)
  X-FORWARDED-HOST: 192.168.0.2
  X-FORWARDED-FOR: 192.168.0.5
  Content-Type: text/xml
  ACCEPT-ENCODING: gzip
[08/Sep/2016:13:44:04] HTTP Traceback (most recent call last):
  File "/home/apache/tactic/3rd_party/CherryPy/cherrypy/_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "/home/apache/tactic/3rd_party/CherryPy/cherrypy/lib/encoding.py", line 193, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/apache/tactic/3rd_party/CherryPy/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/apache/tactic/3rd_party/CherryPy/cherrypy/_cptools.py", line 353, in default
    body = subhandler(*(vpath + rpcparams), **params)
  File "/home/apache/tactic/src/pyasm/prod/service/api_xmlrpc.py", line 278, in new
    ticket = my.init(original_ticket)
  File "/home/apache/tactic/src/pyasm/prod/service/api_xmlrpc.py", line 628, in init
    Project.get()
  File "/home/apache/tactic/src/pyasm/biz/project.py", line 256, in get
    raise TacticException("No project [%s] exists" % project_name)
TacticException: No project [VFX] exists

127.0.0.1 - - [08/Sep/2016:13:44:04] "POST /tactic/default/Api/ HTTP/1.1" 200 278 "" "xmlrpclib.py (Windows)"
```

Couple of things:

My client machine is a windows 10 pro machine. I have Tactic handler on C:\TACTIC-Handler\

My Tactic Server is on a linux machine (fedora 23 server)

Is there a reason why it is looking for a project called VFX? I cannot find that query in any of the python scripts on Tactic-Handler.

thanks for your help.

**Comment by listyque** [comment]
You might need to generate new ticket, because info about project exists in ticket hash.
Or you can wait some time and get new version, where you can have many projects at the same time.[https://1drv.ms/i/s!AvJ4yJPTBglwnJsjDeFR7Oco2kW11g](url)

**Comment by quaam** [comment]
thanks for the reply. I will try generating a new ticket for now, while the new version comes out. 

How do you generate the new ticket? That is in the config window, correct? How do you open that config window again?

**Comment by quaam** [comment]
is there a way to do it?

**Comment by listyque** [comment]
Yup, got to regedit HKEY_CURRENT_USER > SOFTWARE > Tactic Handler > TACTIC Handling Tool > environment.
There by shuffling keys you can change project, user,  delete ticket (then it generates again).
Or you can run TH and click Menu >  Configuration. Type Username and pass and click Generate new Ticket, then restart. After that open Configuration again, go to project page, right-click on desired project and push save and restart.
